language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  # - jruby-18mode
  # - jruby-19mode
  # - jruby-head
  # - rbx-18mode
  # - rbx-19mode
  - ree
  # - ruby-head
# env:
#   - DB=mysql
#   - DB=postgresql
#   - DB=sqlite3
before_script:
  - bundle exec rake db:create:all || true
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
